import type { Pointer } from 'bun:ffi';

export type { HRESULT, UINT } from '@bun-win32/core';

export const DXGI_CREATE_FACTORY_DEBUG = 0x0000_0001;

export enum DXGI_ADAPTER_FLAG {
  DXGI_ADAPTER_FLAG_FORCE_DWORD = 0xffff_ffff,
  DXGI_ADAPTER_FLAG_NONE = 0,
  DXGI_ADAPTER_FLAG_REMOTE = 1,
  DXGI_ADAPTER_FLAG_SOFTWARE = 2,
}

export enum DXGI_ADAPTER_FLAG3 {
  DXGI_ADAPTER_FLAG3_ACG_COMPATIBLE = 4,
  DXGI_ADAPTER_FLAG3_FORCE_DWORD = 0xffff_ffff,
  DXGI_ADAPTER_FLAG3_KEYED_MUTEX_CONFORMANCE = 0x20,
  DXGI_ADAPTER_FLAG3_NONE = 0,
  DXGI_ADAPTER_FLAG3_REMOTE = 1,
  DXGI_ADAPTER_FLAG3_SOFTWARE = 2,
  DXGI_ADAPTER_FLAG3_SUPPORT_MONITORED_FENCES = 8,
  DXGI_ADAPTER_FLAG3_SUPPORT_NON_MONITORED_FENCES = 0x10,
}

export enum DXGI_GPU_PREFERENCE {
  DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE = 2,
  DXGI_GPU_PREFERENCE_MINIMUM_POWER = 1,
  DXGI_GPU_PREFERENCE_UNSPECIFIED = 0,
}

export type LPLPVOID = Pointer;
export type REFIID = Pointer;
